[project]
authors = ["pdimens <pdimens@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "haplotagging_simulations"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[environments]
default = ["mimick"]
harpy = ["harpy"]

[feature.mimick.dependencies]
python = ">=3.12"

[feature.harpy.dependencies]
harpy = ">=2"

