reference_genome = "../dmel_genome/dmel_2_3.fa.gz"
samples = ["sample_%02d" % i for i in range(1,11)]
sizes = ["small", "medium", "large", "xl"]
depths = ["0.5", "5", "20"]
platforms = ["pacbio", "ontshort", "ontlong"]
modes = {
    "pacbio" : "--difference-ratio 22:45:33 --length-mean 8000 --length-sd 1000 --length-min 2000 --length-max 20000",
    "ontshort" : "--difference-ratio 39:24:36 --length-mean 3000 --length-sd 1000",
    "ontlong" : "--difference-ratio 39:24:36 --length-mean 50000 --length-sd 20000"
    }

wildcard_constraints:
    runtype = "[a-zA-Z0-9]+"

rule all:
    default_target: True
    input:
        expand("sv/{sample}.{runtype}.{size}.{depth}.bcf", sample = samples, runtype =platforms, size = sizes, depth = depths),
        expand("logs/{sample}.{runtype}.{size}.{depth}.lengthdist", sample = samples, runtype =platforms, size = sizes, depth = depths)
    message:
        "Complete!"

rule simluate_longreads:
    input:
        geno = "../simulated_variants/inversions_snps_genomes/{size}/{sample}.snp_inv.hap{hap}.fasta.gz",
        model = "models/QSHMM-ONT-HQ.model"
    output:
        temp(expand("{{sample}}.{{runtype}}.{{size}}.{{depth}}.{{hap}}_{chunk}.fastq", chunk = ["%04d" % i for i in range(1,8)]))
    log:
        "logs/{sample}.{runtype}.{size}.{depth}.{hap}.log"
    params:
        config = lambda wc: modes[wc.get("runtype")],
        depth = lambda wc: "--depth " + wc.get("depth"),
        prefix = ".".join([wc.get(i) for i in ["sample", "runtype", "size", "depth", "hap"]])
    message:
        "Simulating reads: {wildcards.sample} {wildcards.runtype}.{wildcards.size}.{wildcards.depth}.haplotype_{wildcards.hap}"
    conda:
        "envs/longreads.yaml"
    shell:
        """
        pbsim --strategy wgs --method qshmm --seed 6969 --qshmm {input.model} \\
            --genome {input.geno} {params.depth} {params.config} \\
            --prefix {params.prefix} --id-prefix {params.prefix} 2> {log} &&
            rm {params.prefix}*.maf {params.prefix}*.ref         
        """

rule merge_fastq:
    input:
        expand("{{sample}}.{{runtype}}.{{size}}.{{depth}}.{hap}_{chunk}.fastq", hap = [1,2], chunk = ["%04d" % i for i in range(1,8)])
    output:
        "{sample}.{runtype}.{size}.{depth}.fq"
    params:
        lambda wc: modes[wc.get("runtype")]
    message:
        "Concatenating fastq: {wildcards.sample} {wildcards.runtype}.{wildcards.size}.{wildcards.depth}"
    shell:
        "cat {input} > {output}"

rule compress:
    input:
        "{sample}.{runtype}.{size}.{depth}.fq"
    output:
        "{sample}.{runtype}.{size}.{depth}.fq.gz"
    threads:
        6
    conda:
        "envs/longreads.yaml"
    message:
        "Compressing: {input}"
    shell:
        "pigz -p {threads} {input}"

rule length_distribution:
    input:
        "{sample}.{runtype}.{size}.{depth}.fq.gz"
    output:
        "logs/{sample}.{runtype}.{size}.{depth}.lengthdist"
    message:
        "Creating read length histogram: {wildcards.sample} {wildcards.runtype}.{wildcards.size}.{wildcards.depth}"
    shell:
        """
        awk 'NR%4 == 2 {{lengths[length($0)]++}} END {{for (l in lengths) {{print l, lengths[l]}}}}' <(zcat {input}) > {output}
        """

rule align:
    input:
        geno = reference_genome,
        reads = "{sample}.{runtype}.{size}.{depth}.fq.gz"
    output:
        temp("align/{sample}.{runtype}.{size}.{depth}.sam")
    log:
        "logs/{sample}.{runtype}.{size}.{depth}.align.log"
    threads:
        6
    params:
        lambda wc: "map-ont" if "ont" in wc.get("runtype") else "map-pb" 
    message:
        "Aligning: {wildcards.sample} {wildcards.runtype}.{wildcards.size}.{wildcards.depth} in {params} mode"
    conda:
        "envs/longreads.yaml"
    shell:
        "minimap2 -t {threads} -ax {params} {input} > {output} 2> {log}"

rule filter:
    input:
        "align/{sample}.{runtype}.{size}.{depth}.sam"
    output:
        bam = temp("align/{sample}.{runtype}.{size}.{depth}.filt.bam"),
        bai = temp("align/{sample}.{runtype}.{size}.{depth}.filt.bam.bai")
    log:
        "logs/{sample}.{runtype}.{size}.{depth}.filter.log"
    threads:
        2
    message:
        "Filtering and sorting:  {wildcards.sample} {wildcards.runtype}.{wildcards.size}.{wildcards.depth}"
    conda:
        "envs/longreads.yaml"
    shell:
        """
        samtools view -h -F 4 -q 20 {input} | 
            samtools sort -O bam -l 0 -m 4G --write-index -o {output.bam}##idx##{output.bai} 2> {log}
        """

rule mark_duplicates:
    input:
        bam = "align/{sample}.{runtype}.{size}.{depth}.filt.bam",
        bai = "align/{sample}.{runtype}.{size}.{depth}.filt.bam.bai"
    output:
        bam = "align/{sample}.{runtype}.{size}.{depth}.bam",
        bai = "align/{sample}.{runtype}.{size}.{depth}.bam.bai"
    log:
        "logs/{runtype}.markduplicates.log"
    threads:
        4
    message:
        "Marking duplicates:  {wildcards.sample} {wildcards.runtype}.{wildcards.size}.{wildcards.depth}"
    conda:
        "envs/longreads.yaml"
    shell:
        "sambamba markdup -t {threads} -l 0 {input.bam} {output.bam} 2> {log}"

rule call_variants:
    input:
        gen = genome,
        reads = "align/{sample}.{runtype}.{size}.{depth}.bam"
    output:
        "sv/{sample}.{runtype}.{size}.{depth}.bcf"
    params:
        lambda wc: "ont" if "ont" in wc.get("runtype") else "pb" 
    message:
        "Calling variants: {wildcards.sample} {wildcards.runtype}.{wildcards.size}.{wildcards.depth} with mode {params}"
    conda:
        "envs/longreads.yaml"
    shell:
        "delly lr -y {params} -o {output} -g {input}"
